version: 1
provider:
    name: opencloud
    path: "Personal"
    directory: "Backup"
includes:
  - aws
  - azure
  - docker
  - ghostty
  - git
  - gnupg
  - hyper
  - icemenubar
  - kubectl
  - macos
  - magnet
  - mail
  - npm
  - raycast
  - ssh
  - terminal
  - tmux
  - vscode
  - wget
  - zed
excludes:
  - bash
  - bartender
  - bat
  - fig
  - homebrew
  - tmux
  - zsh

